export const HOME_LIST_REQUEST = "HOME_LIST_REQUEST"
export const HOME_LIST_SUCCESS = "HOME_LIST_SUCCESS"
export const HOME_LIST_FAIL = "HOME_LIST_FAIL"


export const HOME_DETAILS_REQUEST = "HOME_DETAILS_REQUEST"
export const HOME_DETAILS_SUCCESS = "HOME_DETAILS_SUCCESS"
export const HOME_DETAILS_FAIL = "HOME_DETAILS_FAIL"